### ISSUE TITLE
Search tags simultaneously with URL titles.

### ISSUE THREAD

**Issue by naveci** [fav-sh/extension#5]
Could you add support for searching into the tags as well? This is a lot quicker than manually selecting tags in the sidebar and is helpfull when the bookmark does not have the tag in the title.

**Comment by sgolovine** [comment]
This is getting addressed in #7

**Comment by sgolovine** [comment]
@naveci The issue has been addressed in 2.0.1. If you use Firefox the update is available in the store. If you use Chrome instructions have been added to the repo on how to install the update manually (sorry)
